### ISSUE TITLE
Broken due to use of System.Timers.Timer

### ISSUE THREAD

**Issue by sarahnorthway** [binamonk/Godot-SnakeCS#1]
This sample throws errors instead of spawning new apples.

The timer method to create them (NewApple) isn't running on the main thread. System.Timers.Timer events run on a thread pool thread in .NET C#. Godot doesn't allow adding or removing nodes from non-main threads, so NewApple fails.

Solution is to swap to a Godot timer in the Scene. Fixed project:

https://drive.google.com/open?id=1MsiomrpHdnLrYEGl36wkzfvhx9hjjvBA&usp=drive_fs

**Comment by binamonk** [comment]
Hi Sarah,

I was able to replicate the error on Godot 4.1. 

Using a Timer Node is the easiest way to fix the problem but I wanted to push the sample to a place where C# developers will find a sample on how to use System.Timers.Timer in Godot.

I will go with CallDeferred to keep the C# Timer in the sample.

Thank you
Dan

https://github.com/binamonk/Godot-SnakeCS/commit/7d13b69dfd6bbbb4d0936227e3bdaee849eb4939
